// <auto-generated />
namespace Pocos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class startofTuesday7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(startofTuesday7));
        
        string IMigrationMetadata.Id
        {
            get { return "202001070849343_start of Tuesday 7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
